# Generated by Django 6.0.4 on 2026-04-14 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='run_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractedarticle',
            name='extraction_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='organisations.extractionjob'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='organisations.keywordcategory'),
        ),
        migrations.AddField(
            model_name='newspaperupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='newspaper_uploads',
            field=models.ManyToManyField(related_name='extraction_jobs', to='organisations.newspaperupload'),
        ),
        migrations.AddField(
            model_name='extractedarticle',
            name='newspaper_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='organisations.newspaperupload'),
        ),
        migrations.AddField(
            model_name='keywordcategory',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_categories', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='extractedarticle',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='newspaperupload',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.publisher'),
        ),
        migrations.AddField(
            model_name='extractedarticle',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('category', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='keywordcategory',
            unique_together={('organisation', 'name')},
        ),
    ]
